# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4aa94702962d24aaf228c5eddf81e0cd011ac76ef275665e5ee3735e98493dc8207ccb1baaf2c2a9e6c4e49472b249e39d6ee6777b22833fad47899320c313b

test:
  secret_key_base: c5b195ac60ed783b5f33b18887cc66babbbd01f22671e0e435d7925b39d36dc8e2ba4046eb8313048bd2442bd28cf9718322436e7125a18e6b8020cc27f200ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
